#!/usr/bin/env python3

# Copyright (c) 2014, Liam Fraser <liam@liamfraser.co.uk>
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
# * Neither the name of Liam Fraser nor the names of its
#   contributors may be used to endorse or promote products derived from this
#   software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import signal
import re
import subprocess
import sys
from gi.repository import Gtk, GObject
import logging

ICON_BASE = "/usr/share/icons/Faenza-Ambiance/status/"
ICON_SIZE = "22"
ICON_EXT = "svg"
UPDATE_INTERVAL = 5

class Battery:
    regex = '^Battery ([0-9]): ([^\s]+), ([0-9]+)%(, (.*))?$'
    
    def __init__(self, acpi_string):
        # Attempt to update our status with the acpi string
        ret = self.update(acpi_string)
        if ret:
            self.valid = True
        else:
            self.valid = False
        
        # We want to keep track of the previous icon file so we're not
        # unnecessarily changing it
        self._prev_icon = None

    def __repr__(self):
        out = "Battery\nID: {0}\n".format(self.id)
        out += "State: {0}\n".format(self.state)
        out += "Charge: {0}%".format(self.charge)

        if self.time_str:
            out += "\nTime: {0}".format(self.time_str)

        return out

    def __eq__(self, other):
        return self.id == other.id

    def update(self, acpi_string):
        m = re.search(Battery.regex, acpi_string)

        if m:
            self.id = m.group(1)
            self.state = m.group(2)
            self.charge = int(m.group(3))
            # Time string includes "until charged" or "remaining"
            self.time_str = m.group(5)

            return True
    
        else:
            logging.debug("Couldn't parse acpi string: {0}".format(acpi_string))
            return False

    def icon_file(self):
        ret = ""

        if self.charge <= 10:
            ret = 'gpm-primary-000{0}.{1}'
        elif self.charge <= 30:
            ret = 'gpm-primary-020{0}.{1}'
        elif self.charge <= 50:
            ret = 'gpm-primary-040{0}.{1}'
        elif self.charge <= 70:
            ret = 'gpm-primary-060{0}.{1}'
        elif self.charge <= 90:
            ret = 'gpm-primary-080{0}.{1}'
        else:
            ret = 'gpm-primary-100{0}.{1}'

        if self.state == "Full" or self.state == "Charging":
            ret = ret.format('-charging', ICON_EXT)
        else:
            ret = ret.format('', ICON_EXT)

        ret = "{0}{1}/{2}".format(ICON_BASE, ICON_SIZE, ret)

        return ret

    def update_icon(self):
        logging.debug("Updating text: {0}".format(self.__repr__()))
        self.icon.set_tooltip_text(self.__repr__())
        
        new_icon = self.icon_file()
        if self._prev_icon != new_icon:
            logging.debug("Updating icon: {0}".format(new_icon))
            self.icon.set_from_file(self.icon_file())
            self._prev_icon = new_icon

    def destroy(self):
        self.icon.set_visible(True)
        self.icon = None
        
class SimpleBatt:
    def _acpi_update(self):
        # Example acpi output:
        # Battery 0: Discharging, 17%, 00:48:08 remaining
        self._acpi_status = subprocess.check_output("acpi")
        self._acpi_status = str(self._acpi_status, encoding = "UTF-8")
        self._acpi_status = self._acpi_status.splitlines()

    def _find_batts(self):
        for line in self._acpi_status:
            b = Battery(line)

            # Only add the battery if it's valid and there is not already one
            # in it's place
            if (b.valid) and (b not in self.batts):
                # Create the GTK status icon
                b.icon = Gtk.StatusIcon()
                b.update_icon()
                b.icon.set_visible(True)

                self.batts.append(b)

    def __init__(self, debug):
        if debug:
            logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)
        else:
            logging.basicConfig(stream=sys.stderr, level=logging.ERROR)

        self._acpi_update()
        self.batts = []
        self._find_batts()

    def _gtk_update(self):
        logging.debug("Updating")
        # GTK calls this update function
        # Update our acpi data, then update each battery
        self._acpi_update()

        # Try and find any new batteries
        self._find_batts()

        # Update each battery
        count = 0
        for b in self.batts:
            logging.debug("Attempting to fetch self._acpi_status[{0}]...".format(count))
            logging.debug(self._acpi_status[count])

            ret = False
            try:
                ret = b.update(self._acpi_status[count])
            except IndexError:
                logging.debug("Couldn't find battery {0}".format(count))

            if ret == False: 
                # Battery probably no longer exists, destroy it
                b.destroy()
                self.batts.remove(b)
            else:
                # Otherwise update the batteries icon and increment the count
                b.update_icon()
                count += 1

        # Make sure we run again
        GObject.timeout_add_seconds(UPDATE_INTERVAL, self._gtk_update)


    def gtk_start(self):
        # Set a timer to call the gtk_update function
        GObject.timeout_add_seconds(UPDATE_INTERVAL, self._gtk_update)
 
        Gtk.main()

if __name__ == "__main__":
    # Make sure Ctrl + C works
    signal.signal(signal.SIGINT, signal.SIG_DFL)

    # Check arguments
    debug = False
    for arg in sys.argv:
        if arg == "-d" or arg == "--debug":
            debug = True
 
    # Start application
    sb = SimpleBatt(debug)
    sb.gtk_start()
